### ISSUE TITLE
Possibility of creating an encryptor

### ISSUE THREAD

**Issue by deadkex** [AltimorTASDK/RLUPKTool#3]
Hey there.
Would it be possible to encrypt a decrypted upk file?
Decrypting -> exchanging the tga file -> encrypting -> custom decal?

**Comment by AltimorTASDK** [comment]
Yes, but this project is out of date anyways.

**Comment by deadkex** [comment]
But it still works

**Comment by deadkex** [comment]
The problem is changing the whole process around to encrypt. And i simply have no idea about how it works... i would have to reverse engineer your work.
